create initial screens
rbalves/find-devs-app pull request #6
Opened 2022-09-09 23:15 UTC by PauloBragaDev

### **O que está sendo entregue?**

**- Splash Screen:** 
  Tela onde verifica se existe token salvo no AsyncStorage se existir encaminha para tela Home, senão para preload.

**- Preload Screen:** 
  Opções de logar ou criar conta.

**- Login Screen:** 
  Tela de login, apenas visual e aplicado modo dark.
  
**Navigators**
  **- MainStack:** 
  Agrupamento de todas as telas e depois importado dentro de App.tsx

2022-09-09 23:20 UTC, rbalves commented on src/screens/home/index.tsx
> +                bg: "#044D65"
Sugiro adicionar as cores nos arquivos de estilos: `src/styles/base.ts`

2022-09-09 23:23 UTC, rbalves commented on src/screens/splash/index.tsx
> +    }, []);
Talvez seja interessante criar um hook customizado. Dessa maneira, é possível reaproveitar a lógica em outras telas, caso seja necessário.
Referência: https://pt-br.reactjs.org/docs/hooks-custom.html

2022-09-09 23:24 UTC, rbalves requested changes
Sugiro adicionar as cores no arquivo de estilos e usar as constantes criadas: **_src/styles/base.ts_**

2022-09-09 23:27 UTC, rbalves commented
É necessário resolver os conflitos apresentados!

2022-09-12 19:40 UTC, PauloBragaDev commented on src/screens/splash/index.tsx
> +    }, []);
Opa bem legal! Porém acredito que neste projeto não será necessário fazer esta mesma verificação em outras  telas.

2022-09-13 22:45 UTC, rbalves approved these changes

2022-09-14 23:49 UTC, merged