Init Screen Search
rbalves/find-devs-app pull request #7
Opened 2022-09-10 07:26 UTC by ajuniodx

- Criação da Screen dá página de busca
- Layout base para poder começar a implementação da função de busca/filtar
-  Ajuste Inicial na Screen do React Navigation para seguir o Style Guide

2022-09-10 11:35 UTC, rbalves requested changes
Sugiro adicionar as cores no arquivo de estilos e usar as constantes criadas: src/styles/base.ts

2022-09-11 22:18 UTC, alisonglima approved these changes

2022-09-13 22:45 UTC, rbalves approved these changes

2022-09-14 13:11 UTC, rbalves requested changes
Aguardando as correções

2022-09-17 02:51 UTC, ajuniodx commented
Pessoal, fiz as devidas melhorias se puderem avaliar

2022-09-21 00:03 UTC, rbalves approved these changes

2022-09-21 00:48 UTC, merged